name: reproductor
description: "A new Flutter project."
version: 1.0.0+1
environment:
  sdk: '>=3.2.5 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^0.13.3  # Agrega esta línea para la dependencia http
  path: ^1.8.0  # Agrega esta línea para la dependencia path
  audioplayers: ^0.20.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
